name: "Blazemeter"

env:
  apiKey: ${{ secrets.APIKEY }}
  apiSecret: ${{ secrets.APISECRET }}
  createTest: "true"
  inputStartFile: "PerfTest01.jmx"
  testName: "Sample"
  projectID: "2161675"
  #testID: "13554278"
  continuePipeline: "false"
  showTailLog: "false"
  reportName: Test1030

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Run Blazemeter test          
        uses: BlazeRunner-BZR/Github-Action@v8.2
        id: run-test
        with:
          apiKey: ${{env.apiKey}}
          apiSecret: ${{env.apiSecret}}
          createTest: ${{env.createTest}}
          inputStartFile: ${{env.inputStartFile}}
          testName: ${{env.testName}}
          projectID: ${{env.projectID}}
          #testID: ${{vars.testID}}
          reportName: ${{env.reportName}}
          continuePipeline: ${{env.continuePipeline}}
          showTailLog: ${{env.showTailLog}}
